const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');
const [hdc,target,mode,output]=process.argv.slice(2);if(!hdc||!target||!['debug','release'].includes(mode)||!output)throw new Error('Usage: HDC TARGET debug|release NEW_OUTPUT_DIR');
if(fs.existsSync(output))throw new Error('Refusing to overwrite evidence');fs.mkdirSync(output,{recursive:true});
const app='dev.expo.harmony.i0',prefix='lane-b-fixture://fixture/';const quote=s=>"'"+String(s).replaceAll("'","'\\''")+"'";
const command=(...args)=>execFileSync(hdc,['-t',target,...args],{encoding:'utf8',timeout:30000,maxBuffer:48*1024*1024}).trim();const shell=(...args)=>command('shell',args.map(quote).join(' '));const pause=ms=>new Promise(r=>setTimeout(r,ms));
let pid,coreBoot,fontBoot,latest,log='';let seen=new Set(),lines=[];
function read(){const snapshot=shell('hilog','-x','-P',pid);for(const line of snapshot.split('\n'))if(!seen.has(line)){seen.add(line);lines.push(line)}log=lines.join('\n');assert.ok(!/I0_FONT=.*"kind":"failure"|I0_MODULE_FAIL=|I0_STALE_ASSET_|EXPO_CORE_STALE_|EXPO_CORE_PUBLIC_RELOAD_ERROR=/.test(log),'Failure/stale marker');return log}
async function until(fn,message){for(let i=0;i<90;i++){read();if(fn())return;await pause(500)}throw new Error(message+'\n'+log.slice(-12000))}
const fontRows=()=>log.split('\n').filter(l=>l.includes('I0_FONT=')).map(l=>JSON.parse(l.slice(l.indexOf('I0_FONT=')+'I0_FONT='.length)));
const linkingRows=()=>log.split('\n').filter(l=>l.includes('I0_LINKING=')).map(l=>JSON.parse(l.slice(l.indexOf('I0_LINKING=')+'I0_LINKING='.length)));
const start=uri=>{const output=shell('aa','start','-b',app,'-a','EntryAbility',...(uri?['-U',uri]:[]));if(/^\[Fail\]|^error:/im.test(output))throw new Error(output);return output};
function save(name){read();fs.writeFileSync(path.join(output,name+'.log'),log)}
async function waitComplete(){await until(()=>{const f=fontRows().filter(r=>r.boot===fontBoot);const segment=log.slice(log.lastIndexOf('EXPO_CORE_BOOT='));return f.some(r=>r.kind==='public-pass')&&f.some(r=>r.kind==='material-layout')&&segment.includes('I0_ASSET_PASS=')},'Font/I0 did not complete')}
function check(name,reload=false){save(name);execFileSync(process.execPath,[path.resolve(__dirname,'check-log.cjs'),path.join(output,name+'.log')],{stdio:'pipe'});execFileSync(process.execPath,[path.resolve(__dirname,'../tools/check-i0-log.cjs'),path.join(output,name+'.log'),mode,...(reload?['--reload']:[])],{stdio:'pipe'})}
async function cold(uri,name){shell('aa','force-stop',app);seen=new Set();lines=[];log='';const startOutput=start(uri);fs.appendFileSync(path.join(output,'starts.jsonl'),JSON.stringify({uri,startOutput})+'\n');for(let i=0;i<60;i++){pid=shell('pidof',app);if(/^\d+$/.test(pid))break;await pause(500)}assert.match(pid,/^\d+$/);latest=uri??null;await until(()=>fontRows().some(r=>r.kind==='top-level')&&linkingRows().some(r=>r.kind==='ready'),'Cold startup missing');fontBoot=fontRows().find(r=>r.kind==='top-level').boot;coreBoot=JSON.parse(log.split('EXPO_CORE_BOOT=')[1].split('\n')[0]).id;assert.equal(linkingRows().find(r=>r.kind==='top-level').latest,latest);await waitComplete();check(name);console.log(JSON.stringify({name,pid,fontBoot,coreBoot}))}
async function warm(suffix){const url=prefix+suffix;start(url);latest=url;await until(()=>linkingRows().some(r=>r.kind==='event'&&r.url===url)&&linkingRows().some(r=>r.kind==='hook'&&r.url===url),'Warm link missing');save(suffix)}
function findBounds(tree,label){let found=[];function walk(n){if(!n||typeof n!=='object')return;const a=n.attributes;if(a?.visible==='true'&&Object.values(a).map(String).includes(label)){const v=String(a.bounds).match(/\d+/g)?.map(Number);if(v?.length===4)found.push(v)}for(const value of Object.values(n))walk(value)}walk(tree);assert.ok(found.length,'Missing '+label);return found.sort((a,b)=>(a[2]-a[0])*(a[3]-a[1])-(b[2]-b[0])*(b[3]-b[1]))[0]}
function dumpAndScreenshot(name){const remoteLayout='/data/local/tmp/font-layout.json',remotePng='/data/local/tmp/font-screen.jpeg';shell('uitest','dumpLayout','-p',remoteLayout);command('file','recv',remoteLayout,path.join(output,name+'.layout.json'));shell('snapshot_display','-f',remotePng);command('file','recv',remotePng,path.join(output,name+'.jpeg'));const tree=JSON.parse(fs.readFileSync(path.join(output,name+'.layout.json')));findBounds(tree,'font-material-icon');findBounds(tree,'font-fallback-glyph');const analysis=execFileSync('python3',[path.resolve(__dirname,'analyze-screenshot.py'),path.join(output,name+'.layout.json'),path.join(output,name+'.jpeg')],{encoding:'utf8'});fs.writeFileSync(path.join(output,name+'.analysis.json'),analysis)}
async function reload(round){await waitComplete();let acknowledged=false,previousFont=fontBoot,previousCore=coreBoot;for(let attempt=1;attempt<=3&&!acknowledged;attempt++){const remote='/data/local/tmp/font-reload-layout.json',local=path.join(output,`reload-layout-${round}-${attempt}.json`);shell('uitest','dumpLayout','-p',remote);command('file','recv',remote,local);const bounds=findBounds(JSON.parse(fs.readFileSync(local)),'Reload through Expo public API');const before=log.split('EXPO_CORE_PUBLIC_RELOAD_REQUEST=').length;const response=shell('uitest','uiInput','click',String(Math.round((bounds[0]+bounds[2])/2)),String(Math.round((bounds[1]+bounds[3])/2)));fs.appendFileSync(path.join(output,'reload-clicks.jsonl'),JSON.stringify({round,attempt,bounds,response})+'\n');for(let p=0;p<8;p++){await pause(500);read();if(log.split('EXPO_CORE_PUBLIC_RELOAD_REQUEST=').length>before){acknowledged=true;break}}}assert.ok(acknowledged,'Public reload input not acknowledged');await until(()=>fontRows().some(r=>r.kind==='top-level'&&r.boot!==previousFont),'New Font boot missing');fontBoot=fontRows().filter(r=>r.kind==='top-level').at(-1).boot;coreBoot=JSON.parse(log.split('EXPO_CORE_BOOT=').at(-1).split('\n')[0]).id;assert.notEqual(coreBoot,previousCore);assert.equal(linkingRows().filter(r=>r.kind==='top-level').at(-1).latest,latest);await waitComplete();await until(()=>{const tail=log.slice(log.lastIndexOf('EXPO_CORE_PUBLIC_RELOAD_REQUEST='));return tail.includes('EXPO_CORE_INTEROP_NATIVE_LATE_REJECTION destroyed=true')&&tail.includes('EXPO_CORE_VIEW_DELAYED_READ_FINISHED invalid=1 delay=1000')},'Native late evidence missing');check('reload'+round,true);await warm('font-after-reload-'+round);assert.ok(!fontRows().some(r=>r.boot===previousFont&&r.kind==='public-pass'&&r.runId?.includes(String(fontBoot))),'Old Font runtime callback');}
async function run(){const forwards=command('fport','ls');for(const port of ['18080','18081','8081'])assert.ok(forwards.includes(`tcp:${port}`),`Missing HDC reverse mapping ${port}`);await cold(prefix+'font-cold?q=%E8%B5%84%E6%BA%90#v1','cold');dumpAndScreenshot('cold');await warm('font-warm');for(let i=1;i<=3;i++)await reload(i);dumpAndScreenshot('reload3');await pause(35000);check('reload3-after-timeout',true);shell('uitest','uiInput','keyEvent','Home');await pause(1000);start();await pause(4000);await waitComplete();check('foreground',true);save('final');shell('aa','force-stop',app);await cold(prefix+'font-cold-2','cold2');dumpAndScreenshot('cold2');console.log('FONT_PUBLIC_DEVICE_PASS='+mode)}
run().catch(error=>{if(log)fs.writeFileSync(path.join(output,'failure.log'),log);console.error(error);process.exitCode=1});
