# This file was generated by RNOH autolinking.
# DO NOT modify it manually, your changes WILL be overwritten.
cmake_minimum_required(VERSION 3.5)

# @actor RNOH_APP
function(autolink_libraries target)
    add_subdirectory("${OH_MODULES_DIR}/@react-native-ohos/react-native-gesture-handler/src/main/cpp" ./rnoh_gesture_handler)

    set(AUTOLINKED_LIBRARIES
        rnoh_gesture_handler
    )

    foreach(lib ${AUTOLINKED_LIBRARIES})
        target_link_libraries(${target} PUBLIC ${lib})
    endforeach()
endfunction()
