import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { patchOfficialArtifacts } from '../autolinking-patch';
import type { OfficialAutolinkingResult } from '../official-autolinking';
import { HARMONY_PACKAGE_MAPPING } from '../harmony-package-mapping';

/**
 * 任务三测试：官方产物锚点补充。
 * 官方产物形状依据 docs/superpowers/specs/2026-09-09-official-autolink-contract.md。
 */

let projectRoot: string;
let harmonyDir: string;

beforeEach(() => {
  projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'ehc-patch-test-'));
  harmonyDir = path.join(projectRoot, 'harmony');
  fs.mkdirSync(harmonyDir, { recursive: true });
});

afterEach(() => {
  fs.rmSync(projectRoot, { recursive: true, force: true });
});

const OFFICIAL_ETS = [
  '/*',
  ' * This file was generated by RNOH autolinking.',
  ' */',
  "import type { RNPackageContext, RNOHPackage } from '@rnoh/react-native-openharmony';",
  "import RNCVideoPackage from '@react-native-ohos/react-native-video';",
  '',
  'export function createRNOHPackages(ctx: RNPackageContext): RNOHPackage[] {',
  '  return [',
  '    new RNCVideoPackage(ctx),',
  '  ];',
  '}',
  '',
].join('\n');

const OFFICIAL_CPP = [
  '// clang-format off',
  '#pragma once',
  '#include "RNOH/Package.h"',
  '#include "RNCVideoPackage.h"',
  '',
  'std::vector<rnoh::Package::Shared> createRNOHPackages(const rnoh::Package::Context &ctx) {',
  '  return {',
  '    std::make_shared<rnoh::RNCVideoPackage>(ctx),',
  '  };',
  '}',
  '',
].join('\n');

const OFFICIAL_CMAKE = [
  'cmake_minimum_required(VERSION 3.5)',
  '',
  'function(autolink_libraries target)',
  '    add_subdirectory("${OH_MODULES_DIR}/@react-native-ohos/react-native-video/src/main/cpp" ./rnoh_video)',
  '',
  '    set(AUTOLINKED_LIBRARIES',
  '        rnoh_video',
  '    )',
  '',
  '    foreach(lib ${AUTOLINKED_LIBRARIES})',
  '        target_link_libraries(${target} PUBLIC ${lib})',
  '    endforeach()',
  'endfunction()',
  '',
].join('\n');

const DEEP_OH = JSON.stringify({
  name: 'root',
  dependencies: {
    '@react-native-ohos/react-native-video':
      'file:../../../../../../../tmp/ehc-fixture/node_modules/@react-native-ohos/react-native-video/harmony/rn_video.har',
    'user-manual-dep': '1.0.0',
  },
}, null, 2);

function officialResult(overrides: Partial<OfficialAutolinkingResult> = {}): OfficialAutolinkingResult {
  return {
    ok: true,
    cliVersion: '0.77.71-fake',
    officialPackages: ['@react-native-ohos/react-native-video'],
    uncoveredPackages: ['@react-native-ohos/react-native-safe-area-context'],
    files: [
      { path: path.join(harmonyDir, 'entry/src/main/ets/RNOHPackagesFactory.ets'), content: OFFICIAL_ETS },
      { path: path.join(harmonyDir, 'entry/src/main/cpp/RNOHPackagesFactory.h'), content: OFFICIAL_CPP },
      { path: path.join(harmonyDir, 'entry/src/main/cpp/autolinking.cmake'), content: OFFICIAL_CMAKE },
      { path: path.join(harmonyDir, 'oh-package.json5'), content: DEEP_OH },
    ],
    ...overrides,
  };
}

/** 安装一个带有效 HAR 的 mapping 包（safe-area-context）。 */
function installSafeArea(): void {
  const pkgDir = path.join(projectRoot, 'node_modules/@react-native-ohos/react-native-safe-area-context');
  fs.mkdirSync(path.join(pkgDir, 'harmony'), { recursive: true });
  fs.writeFileSync(path.join(pkgDir, 'package.json'), JSON.stringify({ name: '@react-native-ohos/react-native-safe-area-context' }));
  fs.writeFileSync(path.join(pkgDir, 'harmony/safe_area.har'), 'har bytes');
}

describe('patchOfficialArtifacts', () => {
  it('mapping 命中的缺口包被补充到三工厂与 oh-package，官方原片段保留', () => {
    installSafeArea();
    const report = patchOfficialArtifacts({
      projectRoot, harmonyDir, official: officialResult(), mapping: HARMONY_PACKAGE_MAPPING,
    });
    expect(report.patched).toEqual(['@react-native-ohos/react-native-safe-area-context']);
    const ets = report.files.find(f => f.path.endsWith('.ets'))!.content;
    expect(ets).toContain("import { SafeAreaViewPackage } from '@react-native-ohos/react-native-safe-area-context/ts';");
    expect(ets).toContain('new SafeAreaViewPackage(ctx),');
    expect(ets).toContain('new RNCVideoPackage(ctx),'); // 官方片段保留
    const cpp = report.files.find(f => f.path.endsWith('Factory.h'))!.content;
    expect(cpp).toContain('#include "SafeAreaViewPackage.h"');
    expect(cpp).toContain('std::make_shared<rnoh::SafeAreaViewPackage>(ctx),');
    const cmake = report.files.find(f => f.path.endsWith('.cmake'))!.content;
    expect(cmake).toContain('resolve_oh_package_cpp(AUTOLINKED_CPP_DIR "@react-native-ohos/react-native-safe-area-context")');
    expect(cmake).toContain('        rnoh_safe_area');
    expect(cmake).toContain('rnoh_video'); // 官方 target 保留
  });

  it('官方 oh-package 深相对路径被改写为项目相对路径，用户依赖保留', () => {
    installSafeArea();
    const report = patchOfficialArtifacts({
      projectRoot, harmonyDir, official: officialResult(), mapping: HARMONY_PACKAGE_MAPPING,
    });
    const oh = report.files.find(f => f.path.endsWith('oh-package.json5'))!.content;
    expect(oh).toContain('"@react-native-ohos/react-native-video": "file:../node_modules/@react-native-ohos/react-native-video/harmony/rn_video.har"');
    expect(oh).toContain('"@react-native-ohos/react-native-safe-area-context": "file:../node_modules/@react-native-ohos/react-native-safe-area-context/harmony/safe_area.har"');
    expect(oh).toContain('"user-manual-dep": "1.0.0"');
  });

  it('HAR 缺失的缺口包跳过并报告原因', () => {
    // 不安装 safe-area-context（node_modules 无该包/HAR）
    const report = patchOfficialArtifacts({
      projectRoot, harmonyDir, official: officialResult(), mapping: HARMONY_PACKAGE_MAPPING,
    });
    expect(report.patched).toEqual([]);
    expect(report.skippedNoHar.map(s => s.package)).toContain('@react-native-ohos/react-native-safe-area-context');
  });

  it('不在 mapping 的未覆盖包进入 remainingGaps', () => {
    installSafeArea();
    const report = patchOfficialArtifacts({
      projectRoot, harmonyDir,
      official: officialResult({ uncoveredPackages: ['@react-native-ohos/react-native-safe-area-context', 'unknown-native-pkg'] }),
      mapping: HARMONY_PACKAGE_MAPPING,
    });
    expect(report.remainingGaps).toEqual(['unknown-native-pkg']);
  });

  it('与官方已有 symbol 同名时报冲突并抛错（不得用去重掩盖）', () => {
    installSafeArea();
    // mapping 中的 video 条目与官方产物中已注册的 RNCVideoPackage 冲突
    const mapping = {
      ...HARMONY_PACKAGE_MAPPING,
      '@react-native-ohos/react-native-safe-area-context': {
        ...HARMONY_PACKAGE_MAPPING['@react-native-ohos/react-native-safe-area-context'],
        etsPackageClassName: 'RNCVideoPackage', // 与官方实例同名
      },
    };
    expect(() => patchOfficialArtifacts({
      projectRoot, harmonyDir, official: officialResult(), mapping,
    })).toThrow(/冲突|RNCVideoPackage/);
  });

  it('官方产物已有该包部分注册（import 残留）时替换残留后补充完整注册', () => {
    installSafeArea();
    // 官方 ETS 产物含 safe-area 的 import 残留（无实例）
    const partialEts = OFFICIAL_ETS.replace(
      "import RNCVideoPackage from '@react-native-ohos/react-native-video';",
      "import RNCVideoPackage from '@react-native-ohos/react-native-video';\nimport { SafeAreaViewPackage } from '@react-native-ohos/react-native-safe-area-context/ts';",
    );
    const report = patchOfficialArtifacts({
      projectRoot, harmonyDir,
      official: officialResult({
        files: officialResult().files.map(f => f.path.endsWith('.ets') ? { ...f, content: partialEts } : f),
      }),
      mapping: HARMONY_PACKAGE_MAPPING,
    });
    const ets = report.files.find(f => f.path.endsWith('.ets'))!.content;
    // import 只出现一次（残留被替换，非重复追加）
    expect(ets.match(/safe-area-context\/ts';/g)?.length).toBe(1);
    expect(ets).toContain('new SafeAreaViewPackage(ctx),');
  });

  it('有 cppSourcePath 的包生成 NODE_MODULES 直连形式的 CMake 片段', () => {
    const pkgDir = path.join(projectRoot, 'node_modules/@react-native-ohos/react-native-webview');
    fs.mkdirSync(path.join(pkgDir, 'harmony'), { recursive: true });
    fs.writeFileSync(path.join(pkgDir, 'package.json'), JSON.stringify({ name: '@react-native-ohos/react-native-webview' }));
    fs.writeFileSync(path.join(pkgDir, 'harmony/rn_webview.har'), 'har bytes');
    const report = patchOfficialArtifacts({
      projectRoot, harmonyDir,
      official: officialResult({ uncoveredPackages: ['@react-native-ohos/react-native-webview'] }),
      mapping: HARMONY_PACKAGE_MAPPING,
    });
    const cmake = report.files.find(f => f.path.endsWith('.cmake'))!.content;
    expect(cmake).toContain('set(AUTOLINKED_CPP_DIR "${NODE_MODULES}/@react-native-ohos/react-native-webview/harmony/rn_webview/src/main/cpp")');
    expect(cmake).toContain('        rnoh_webview');
  });
});
