const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');
const [hdc,target,mode,output]=process.argv.slice(2);if(!hdc||!target||!['debug','release'].includes(mode)||!output)throw new Error('Usage: HDC TARGET debug|release NEW_OUTPUT_DIR');if(fs.existsSync(output))throw new Error('Refusing to overwrite evidence');fs.mkdirSync(output,{recursive:true});
const app='dev.expo.harmony.i0',prefix='lane-b-fixture://fixture/';const q=s=>"'"+String(s).replaceAll("'","'\\''")+"'";const command=(...a)=>execFileSync(hdc,['-t',target,...a],{encoding:'utf8',timeout:30000,maxBuffer:48*1024*1024}).trim();const shell=(...a)=>command('shell',a.map(q).join(' '));const pause=ms=>new Promise(r=>setTimeout(r,ms));
let pid,boot,log='';let seen=new Set(),lines=[];function read(){const s=shell('hilog','-x','-P',pid);for(const l of s.split('\n'))if(!seen.has(l)){seen.add(l);lines.push(l)}log=lines.join('\n');assert.ok(!/I0_STATUS_BAR=.*"kind":"failure"|I0_MODULE_FAIL=|I0_STALE_ASSET_|EXPO_CORE_STALE_|EXPO_CORE_PUBLIC_RELOAD_ERROR=/.test(log));return log}async function until(fn,msg){for(let i=0;i<100;i++){read();if(fn())return;await pause(500)}throw new Error(msg+'\n'+log.slice(-12000))}
const rows=()=>log.split('\n').filter(l=>l.includes('I0_STATUS_BAR=')).map(l=>JSON.parse(l.slice(l.indexOf('I0_STATUS_BAR=')+'I0_STATUS_BAR='.length)));const start=uri=>{const o=shell('aa','start','-b',app,'-a','EntryAbility',...(uri?['-U',uri]:[]));if(/^\[Fail\]|^error:/im.test(o))throw new Error(o);return o};function save(n){read();fs.writeFileSync(path.join(output,n+'.log'),log)}
async function complete(){await until(()=>rows().some(r=>r.boot===boot&&r.kind==='public-pass')&&log.slice(log.lastIndexOf('EXPO_CORE_BOOT=')).includes('I0_ASSET_PASS='),'StatusBar/I0 incomplete')}
function check(n,reload=false){save(n);execFileSync(process.execPath,[path.resolve(__dirname,'check-log.cjs'),path.join(output,n+'.log'),...(reload?['--reload']:[])],{stdio:'pipe'});execFileSync(process.execPath,[path.resolve(__dirname,'../tools/check-i0-log.cjs'),path.join(output,n+'.log'),mode,...(reload?['--reload']:[])],{stdio:'pipe'})}
async function cold(uri,n){shell('aa','force-stop',app);seen=new Set();lines=[];log='';const o=start(uri);fs.appendFileSync(path.join(output,'starts.jsonl'),JSON.stringify({uri,output:o})+'\n');for(let i=0;i<60;i++){pid=shell('pidof',app);if(/^\d+$/.test(pid))break;await pause(500)}assert.match(pid,/^\d+$/);await until(()=>rows().some(r=>r.kind==='snapshot'&&r.label==='component-dark'),'No StatusBar boot');boot=rows().find(r=>r.kind==='snapshot'&&r.label==='component-dark').boot;await complete();check(n)}
function findButton(tree){let b;function w(n){if(!n||typeof n!=='object')return;const a=n.attributes;if(a?.type==='Button'&&a.text==='Reload through Expo public API'&&a.visible==='true')b=String(a.bounds).match(/\d+/g)?.map(Number);for(const v of Object.values(n))w(v)}w(tree);assert.ok(b);return b}
async function reload(round){const previous=boot;let ack=false;for(let a=1;a<=3&&!ack;a++){const remote='/data/local/tmp/status-layout.json',local=path.join(output,`layout-${round}-${a}.json`);shell('uitest','dumpLayout','-p',remote);command('file','recv',remote,local);const b=findButton(JSON.parse(fs.readFileSync(local)));const before=log.split('EXPO_CORE_PUBLIC_RELOAD_REQUEST=').length;shell('uitest','uiInput','click',String((b[0]+b[2])>>1),String((b[1]+b[3])>>1));for(let p=0;p<8;p++){await pause(500);read();if(log.split('EXPO_CORE_PUBLIC_RELOAD_REQUEST=').length>before){ack=true;break}}}assert.ok(ack);await until(()=>rows().some(r=>r.kind==='snapshot'&&r.label==='component-dark'&&r.boot!==previous),'No new StatusBar boot');boot=rows().filter(r=>r.kind==='snapshot'&&r.label==='component-dark').at(-1).boot;await complete();await until(()=>{const t=log.slice(log.lastIndexOf('EXPO_CORE_PUBLIC_RELOAD_REQUEST='));return t.includes('EXPO_CORE_INTEROP_NATIVE_LATE_REJECTION destroyed=true')&&t.includes('EXPO_CORE_VIEW_DELAYED_READ_FINISHED invalid=1 delay=1000')},'Late evidence missing');check('reload'+round,true)}
function screenshot(n){const remote='/data/local/tmp/status-screen.jpeg',local=path.join(output,n+'.jpeg');shell('snapshot_display','-f',remote);command('file','recv',remote,local);const r=execFileSync('python3',[path.resolve(__dirname,'analyze-screenshot.py'),local],{encoding:'utf8'});fs.writeFileSync(path.join(output,n+'.analysis.json'),r)}
async function run(){const forwards=command('fport','ls');for(const port of ['18080','18081','8081'])assert.ok(forwards.includes(`tcp:${port}`));await cold(prefix+'status-cold','cold');screenshot('cold');for(let i=1;i<=3;i++)await reload(i);screenshot('reload3');await pause(35000);check('reload3-after-timeout',true);shell('uitest','uiInput','keyEvent','Home');await pause(1000);start();await pause(5000);await complete();check('foreground',true);save('final');shell('aa','force-stop',app);await cold(prefix+'status-cold-2','cold2');screenshot('cold2');console.log('STATUS_BAR_PUBLIC_DEVICE_PASS='+mode)}
run().catch(e=>{if(log)fs.writeFileSync(path.join(output,'failure.log'),log);console.error(e);process.exitCode=1});
