import mustache from 'mustache';
import JSON5 from 'json5';
import * as fs from 'fs';
import * as path from 'path';
import type { HarmonyCppPackage, HarmonyEtsPackage, HarmonyPackageMappingEntry } from './types';

/**
 * 模板 1：ETS_RNOH_PACKAGES_FACTORY_TEMPLATE
 * 生成 harmony/entry/src/main/ets/RNOHPackagesFactory.ets
 *
 * 字段取自 HarmonyPackageMappingEntry：
 *   - importStatement：完整 import 行（保留 named/default 区分 + /ts 路径后缀）
 *   - etsPackageClassName：new <Class>(ctx)
 *
 * 注：参考 D.5 原模板用 `import {{etsRNOHPackageClassName}} from '{{{ohPackageName}}}'`，
 * 但 safe-area-context 等是 named import 且需 /ts 后缀，无法用单字段表达。
 * 故 Task 3 mapping 预存 importStatement 整行，本模板直接 {{{importStatement}}} 渲染。
 */
const ETS_TEMPLATE = `/*
 * This file was generated by RNOH autolinking.
 * DO NOT modify it manually, your changes WILL be overwritten.
 */
import type { RNPackage, RNPackageContext } from '@rnoh/react-native-openharmony';
{{#etsImports}}
{{{importStatement}}}
{{/etsImports}}

export function createRNOHPackages(ctx: RNPackageContext): RNPackage[] {
  return [
{{#etsPackageClasses}}
    new {{className}}(ctx),
{{/etsPackageClasses}}
  ];
}
`;

/**
 * 模板 2：CPP_RNOH_PACKAGES_FACTORY_TEMPLATE
 * 生成 harmony/entry/src/main/cpp/RNOHPackagesFactory.h
 */
const CPP_TEMPLATE = `/*
 * This file was generated by RNOH autolinking.
 * DO NOT modify it manually, your changes WILL be overwritten.
 */
// clang-format off
#pragma once
#include "RNOH/Package.h"
{{#cppPackages}}
#include "{{className}}.h"
{{/cppPackages}}

std::vector<rnoh::Package::Shared> createRNOHPackages(const rnoh::Package::Context &ctx) {
  return {
{{#cppPackages}}
    std::make_shared<{{typeName}}>(ctx),
{{/cppPackages}}
  };
}
`;

/**
 * 模板 3：CMAKE_AUTOLINKING_TEMPLATE
 * 生成 harmony/entry/src/main/cpp/autolinking.cmake
 *
 * 注意：${OH_MODULES_DIR} / ${AUTOLINKED_LIBRARIES} / ${target} / ${lib} 都是 CMake 变量，
 * 必须在输出里保留字面 `${...}`。这里用 JS 反引号模板字符串，故全部 `\${...}` 转义
 * 防止被 JS 当成插值解释（任务说明原稿漏转义了 ${OH_MODULES_DIR}，已补）。
 */
const CMAKE_TEMPLATE = `# This file was generated by RNOH autolinking.
# DO NOT modify it manually, your changes WILL be overwritten.
cmake_minimum_required(VERSION 3.5)

# @actor RNOH_APP
function(autolink_libraries target)
{{#cmakeLibraries}}
{{#cppSourcePath}}
    set(AUTOLINKED_CPP_DIR "\${NODE_MODULES}/{{{npmPackageName}}}/{{{cppSourcePath}}}")
{{/cppSourcePath}}
{{^cppSourcePath}}
    resolve_oh_package_cpp(AUTOLINKED_CPP_DIR "{{{npmPackageName}}}")
{{/cppSourcePath}}
    add_subdirectory("\${AUTOLINKED_CPP_DIR}" ./{{cmakeLibraryTargetName}})
{{/cmakeLibraries}}

    set(AUTOLINKED_LIBRARIES
{{#cmakeLibraries}}
        {{cmakeLibraryTargetName}}
{{/cmakeLibraries}}
    )

    foreach(lib \${AUTOLINKED_LIBRARIES})
        target_link_libraries(\${target} PUBLIC \${lib})
    endforeach()
endfunction()
`;

export interface AutolinkingResult {
  /** 命中并被链接的 npm 包名（字典序）*/
  linked: string[];
  skipped: Array<{ package: string; reason: string }>;
  /** 生成的四个文件（绝对路径 + 内容）*/
  files: Array<{ path: string; content: string }>;
  managedOhPackageEntries: Array<{ ohPackagePath: string; expected: Record<string, string> }>;
}

function getEtsPackages(lib: HarmonyPackageMappingEntry): HarmonyEtsPackage[] {
  if (lib.etsPackages) return lib.etsPackages;
  if (lib.importStatement && lib.etsPackageClassName) {
    return [{ importStatement: lib.importStatement, classNames: [lib.etsPackageClassName] }];
  }
  return [];
}

function getCppPackages(lib: HarmonyPackageMappingEntry): HarmonyCppPackage[] {
  if (lib.cppPackages) return lib.cppPackages;
  if (lib.cppPackageClassName && lib.cppPackageNamespace !== undefined) {
    return [{ className: lib.cppPackageClassName, namespace: lib.cppPackageNamespace }];
  }
  return [];
}

/**
 * Autolinking 引擎：mapping 命中（node_modules 存在）→ 三 mustache 模板渲染 +
 * oh-package.json5 合并。参考 D.5。
 *
 * 命中规则：mapping 条目的 npmPackageName 在 `<projectRoot>/node_modules/<npmPackageName>`
 * 存在则链接。按 npmPackageName 字典序排序，保证产出稳定（幂等）。
 *
 * oh-package.json5 合并：unmanaged（非 file:../node_modules 形式）保留，
 * managed 段按命中库重生成 `file:../../node_modules/<pkg>/harmony/<har>`，覆盖同名 unmanaged。
 */
export function runAutolinking(opts: {
  projectRoot: string;
  harmonyDir: string;
  mapping: Record<string, HarmonyPackageMappingEntry>;
}): AutolinkingResult {
  const { projectRoot, harmonyDir, mapping } = opts;

  // 1. 命中：mapping 里 npmPackageName 在 node_modules 存在 → 字典序排序（参考 D.7）
  const skipped: Array<{ package: string; reason: string }> = [];
  const libraries = Object.values(mapping)
    .filter(e => {
      const packageDir = path.join(projectRoot, 'node_modules', e.npmPackageName);
      if (!fs.existsSync(packageDir)) return false;
      const harPath = path.join(packageDir, 'harmony', e.harName);
      if (!fs.existsSync(harPath) || fs.statSync(harPath).size === 0) {
        skipped.push({ package: e.npmPackageName, reason: `缺少有效 HAR: ${path.relative(projectRoot, harPath)}` });
        return false;
      }
      return true;
    })
    .sort((a, b) => a.npmPackageName.localeCompare(b.npmPackageName));

  const etsPackages = libraries.flatMap(getEtsPackages);
  const etsImports = Array.from(
    new Map(etsPackages.map(entry => [entry.importStatement, { importStatement: entry.importStatement }])).values(),
  );
  const view = {
    etsImports,
    etsPackageClasses: etsPackages.flatMap(entry => entry.classNames.map(className => ({ className }))),
    cppPackages: libraries.flatMap(getCppPackages).map(entry => ({
      ...entry,
      typeName: entry.namespace === null ? entry.className : `${entry.namespace}::${entry.className}`,
    })),
    cmakeLibraries: libraries.filter(lib => Boolean(lib.cmakeLibraryTargetName)),
  };

  // 2. 三模板渲染
  const ets = mustache.render(ETS_TEMPLATE, view);
  const cpp = mustache.render(CPP_TEMPLATE, view);
  const cmake = mustache.render(CMAKE_TEMPLATE, view);

  // 3. oh-package.json5 合并（参考 D.5 模板 4）
  const ohPkgPath = path.join(harmonyDir, 'oh-package.json5');
  const ohPkgContent = mergeOhPackageDependencies(ohPkgPath, libraries, mapping, '../node_modules');

  const files = [
    { path: path.join(harmonyDir, 'entry/src/main/ets/RNOHPackagesFactory.ets'), content: ets },
    { path: path.join(harmonyDir, 'entry/src/main/cpp/RNOHPackagesFactory.h'), content: cpp },
    { path: path.join(harmonyDir, 'entry/src/main/cpp/autolinking.cmake'), content: cmake },
    { path: ohPkgPath, content: ohPkgContent },
  ];

  const entryOhPkgPath = path.join(harmonyDir, 'entry/oh-package.json5');
  if (fs.existsSync(entryOhPkgPath)) {
    files.push({
      path: entryOhPkgPath,
      content: mergeOhPackageDependencies(entryOhPkgPath, libraries, mapping, '../../node_modules'),
    });
  }

  const expectedFor = (prefix: '../node_modules' | '../../node_modules') => Object.fromEntries(
    libraries.map(lib => [lib.npmPackageName, `file:${prefix}/${lib.npmPackageName}/harmony/${lib.harName}`]),
  );
  const managedOhPackageEntries = [{ ohPackagePath: ohPkgPath, expected: expectedFor('../node_modules') }];
  if (fs.existsSync(entryOhPkgPath)) managedOhPackageEntries.push({ ohPackagePath: entryOhPkgPath, expected: expectedFor('../../node_modules') });

  return {
    linked: libraries.map(l => l.npmPackageName),
    skipped,
    files,
    managedOhPackageEntries,
  };
}

function mergeOhPackageDependencies(
  ohPackagePath: string,
  libraries: HarmonyPackageMappingEntry[],
  mapping: Record<string, HarmonyPackageMappingEntry>,
  nodeModulesRelativePath: '../node_modules' | '../../node_modules',
): string {
  const ohPackage = JSON5.parse(fs.readFileSync(ohPackagePath, 'utf8'));

  const managed: Record<string, string> = {};
  for (const lib of libraries) {
    managed[lib.npmPackageName] = `file:${nodeModulesRelativePath}/${lib.npmPackageName}/harmony/${lib.harName}`;
  }

  const unmanaged: Record<string, string> = {};
  for (const [name, spec] of Object.entries<string>(ohPackage.dependencies || {})) {
    const isAutolinkedHarmonyPackage = Object.prototype.hasOwnProperty.call(mapping, name);
    if (!isAutolinkedHarmonyPackage) unmanaged[name] = spec;
  }
  ohPackage.dependencies = { ...unmanaged, ...managed };
  return JSON5.stringify(ohPackage, { space: 2, quote: '"' }) + '\n';
}
