#include "RNOH/PackageProvider.h"
#include "RNOHPackagesFactory.h"
#include "generated/RNOHGeneratedPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  auto packages = createRNOHPackages(ctx); // <= autolinking
  packages.push_back(std::make_shared<RNOHGeneratedPackage>(
      ctx)); // generated by codegen-harmony v1 on app preBuilt stage)
  // 本文件归你管理：CLI 的 sync/install/uninstall 不会覆盖它。
  // 如需注册自定义 C++ Package，直接在下方 push_back，例如：
  //   packages.push_back(std::make_shared<MyCustomPackage>(ctx));
  return packages;
}